ImproveSingleItemComponent
UCB-TallerDeDesarrollo/NCV pull request #142
Opened 2022-10-18 14:49 UTC by CarolinaMelendez

2022-10-18 21:05 UTC, OmkrPuas commented
Buena implementación de pruebas! Servirá mucho para los que tienen problemas con las pruebas aun!

2022-10-18 21:42 UTC, kevca87 requested changes

2022-10-18 21:42 UTC, kevca87 commented on web-ui/src/Components/SingleItemCard.jsx
>        for (const prop in element ){
La alineación de este for y de la llave previa es al nivel de const.

2022-10-18 21:42 UTC, kevca87 commented on web-ui/src/Components/SingleItemCard.jsx
>                  contentOneElement =  " ----- "
Me parece mas propicio que si es null no se muestre nada. Ósea ni el titulo de la `prop`. Tal vez cambiar con solo hacer push `if (element[prop] != null)`, y de igual manera no se deberían recibir "". Si es que se recibe en algún form se esta mandando eso hay que corregir. Pero si se recibe "" a mi criterio se debe mostrar "".

2022-10-18 21:42 UTC, kevca87 commented on web-ui/src/Components/SingleItemCard.jsx
>  const SingleItemCard = ({title="" , element, imageUrl = "none" , imageCirle=true}) => {
en lugar de "none" convendría usar `null` para mostrar la ausencia de valor, en consecuencia en la línea 71 tb cambiar.

2022-10-18 21:42 UTC, kevca87 commented on web-ui/src/Components/SingleItemCard.jsx
>      if (imageUrl != "none"){
Cambiar por `!= null`

2022-10-18 21:42 UTC, kevca87 commented on web-ui/src/Components/SingleItemCard.jsx
> +                                            {detailsElement[i]}
aquí se puede cambiar `{detailsElement[i]}` por `{n}` de igual forma conviene cambiar `n` al definir el map por `elem` o `detail` para que sea mas descriptivo.

2022-10-18 21:42 UTC, kevca87 commented on web-ui/src/Components/SingleItemCard.jsx
> +        contentCard.push(
Este bloque es igual al de las líneas `76 - 86` se puede sacar del if y del else para que reducir código duplicado. Y solo modificar dentro del if y del else los atributos que cambian que son `sm` y `md` de `Box`

2022-10-18 21:42 UTC, kevca87 commented on web-ui/src/Components/SingleItemCard.jsx
> +    if( contentCard.length==2){
Esta condición es innecesaria, basta con retornar siempre `<Card ... > {contentCard.map()...}` si solo hay uno, solo verificara ese 1 si hay mas de uno entonces tb lo añadira.

2022-10-18 21:46 UTC, kevca87 commented
No están pasando los test

2022-10-19 02:59 UTC, kevca87 approved these changes

2022-10-19 11:12 UTC, merged