refactoring filter by program
UCB-TallerDeDesarrollo/NCV pull request #294
Opened 2022-11-25 01:54 UTC by JuanPaauul

2022-11-25 02:03 UTC, Diego377 approved these changes

2022-11-25 02:04 UTC, Diego377 requested changes
Review the tests

2022-11-26 14:28 UTC, FranRosem approved these changes
Buena okseneada

2022-11-26 14:42 UTC, Diego377 approved these changes

2022-11-26 15:33 UTC, tiaraRS approved these changes

2022-11-26 16:51 UTC, merged